model: efficientnet_b0 #convnext_tiny #yolov8n.pt #EUPE-ViT-T # #vit_tiny_patch16_224
dataset: RGZ20k
save_dir: /home/users/l/lastufka/scratch/lejepa/efficientnet_rgz20k
checkpoint: /home/users/l/lastufka/scratch/lejepa/efficientnet_rgz20k/checkpoint_18.pt
run_name: efficientnet_rgz20k
bs: 16
epochs: 100
lr: 3e-5
lamb: 0.05
proj_dim: 16 # 16 #128
mlp_dim: 512
V: 2
V_local: 8
seed: 14
imsize: 224
yolo_spatial: false